spring.application.name=app

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LibraryDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver



spring.web.resources.static-locations=classpath:/static/

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quorixlibrarynotifications@gmail.com
spring.mail.password=cnkl tqxm hlrn jsdx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# Library Email Settings
library.email.from=noreply@quorixlibrary.com
library.email.admin=admin@quorixlibrary.com