spring.application.name=app

# SQL Server JDBC URL with integrated security and TLS enabled
# Option 1: Trust the server certificate (simpler for development)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LibraryDB;integratedSecurity=true;encrypt=true;trustServerCertificate=true;

# No need for username/password when using Windows Authentication
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.web.resources.static-locations=classpath:/static/


# ===============================================
# EMAIL SENDER CONFIGURATION (Gmail Example)
# ===============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=it24102433@my.sliit.lk
spring.mail.password=fwoa fqcs agxg wgph
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true