spring.application.name=app

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LibraryDB;integratedSecurity=true;encrypt=true;trustServerCertificate=true;

# No need for username/password when using Windows Authentication
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.web.resources.static-locations=classpath:/static/

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_LIBRARY_APPLICATION_GMAIL
spring.mail.password=APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Library Email Settings
library.email.from=noreply@quorixlibrary.com
library.email.admin=admin@quorixlibrary.com
